linters:
  enable:
  - asciicheck
  - unused
  - depguard
  - errcheck
  - errorlint
  - forbidigo
  - gofmt
  - goimports
  - gosec
  - gocritic
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace
linters-settings:
  forbidigo:
    exclude_godoc_examples: false
output:
  uniq-by-line: false
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
    - forbidigo
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  timeout: 10m
